name: "Hello Actions"
description: "Greet someone"
author: "canadiyaman@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "Can"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
